# Meta information
name:                 "Adam Liter"
description:          "Adam Liter's personal webpage."
keywords:             "Adam, Adam Liter, Liter, linguistics, semantics, syntax, philosophy of language, child language acquisition, web development, development, web"
url:                  "https://adamliter.org"
shiny-url:            "https://shiny.adamliter.org"


# Global configuration
source:               .
destination:          ./_site
plugins_dir:          ./_plugins
layouts_dir:          ./_layouts
data_dir:             ./_data
includes_dir:         ./_includes
collections:          null


# Handling reading
safe:                 false
include:              []
exclude:              ["_site", "bootstrap", "README.md", "Rakefile", "blog", ".ruby-gemset", ".ruby-version", "circle.yml", "Gemfile", "Gemfile.lock", "vendor"]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"


# Filtering content
show_drafts:          null
limit_posts:          0
future:               false
unpublished:          false


# Plugins
whitelist:            []
gems:                 [jekyll-paginate, jekyll-gist, jekyll-sitemap]


# Conversion
markdown:             kramdown
highlighter:          rouge
lsi:                  false
excerpt_separator:    "\n\n"
incremental:          false


# Serving locally
detach:               false
port:                 4000
host:                 127.0.0.1
baseurl:              "" # does not include hostname


# Outputting
permalink:            pretty
paginate:             10
paginate_path:        /page:num
timezone:             null
quiet:                false
defaults:
  -
    scope:
      path:           ""
      type:           "posts"
    values:
      layout:         "post-default"
      author:         "Adam Liter"
  -
    scope:
      path:           ""
      type:           "pages"
    values:
      layout:         "default"
  - 
    scope:
      path:           "updates"
      type:           "posts"
    values:
      sitemap:        false
sass:
  style:              compressed

# Markdown processors
rdiscount:
  extensions:         []

redcarpet:
  extensions:         []

kramdown:
  input:              GFM
  syntax_highlighter: rouge
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  smart_quotes:       lsquo,rsquo,ldquo,rdquo
  enable_coderay:     false